#line 1 "/home/cai/projects/basic/compiler/qblex.cpp"

#line 3 "/home/cai/projects/basic/compiler/qblex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[260] =
    {   0,
        6,    6,    0,    0,    0,    0,    0,    0,   70,   63,
       48,    6,   46,   63,   37,   63,    4,   49,   47,   49,
       49,   49,   49,   58,    5,   44,   40,   42,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   34,   38,   65,   66,   65,   67,   68,
       69,   48,    6,    0,   62,   36,    4,   34,   57,   56,
       33,   59,    2,    3,    0,   58,    0,    5,   43,   45,
       39,   41,   61,   60,   60,   60,   29,   60,   60,   60,
       60,   60,   14,   60,   60,   21,   60,   60,   60,   60,
       60,   60,   38,   52,   60,   60,   60,   60,   60,   25,

       60,   60,   60,   64,    3,    0,   59,   35,   60,   30,
       60,   60,   60,   60,   60,   24,   60,   50,   28,   31,
       60,   37,   51,   46,   60,    1,   60,   60,   27,   18,
       60,   60,   60,   60,   60,   22,   20,    0,   60,   60,
       60,   60,   60,   60,   60,   60,   28,   60,   60,   26,
       60,   60,   60,   19,   54,   12,   60,   60,   60,    0,
        0,    0,    0,   60,   60,   14,   60,   60,   60,   53,
       55,   60,   60,   32,   60,   60,   60,   60,   13,    0,
       60,   22,    0,    0,   14,    0,    0,    0,   10,   60,
       60,    7,   60,   60,   60,   23,   27,   15,   60,    0,

       60,   10,    0,    0,    7,    0,   60,   60,   60,   60,
       60,   60,    0,   60,   60,    0,   11,    0,    0,    0,
        0,   60,   60,   60,    9,   17,   50,    0,   60,   60,
       11,    0,    0,    0,    9,   60,   16,   60,    0,   15,
       60,    0,   16,    0,   60,   60,   15,   18,    0,    0,
        8,   60,    8,    0,   60,    0,    7,    7,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   10,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   30,   31,   32,   33,   34,   35,
       30,   36,   37,   38,   39,   30,   40,   30,   41,   30,
        1,   42,    1,   43,   30,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   30,   30,   53,   54,   55,
       56,   57,   30,   58,   59,   60,   61,   30,   62,   30,
       63,   30,    1,   64,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1
    } ;

static const flex_int16_t yy_base[267] =
    {   0,
        0,    0,   62,   63,  642,  641,    0,    0,  643,  646,
      640,  638,  646,   64,  646,  632,    0,  646,  628,  622,
       52,  621,   60,   62,  633,   60,  616,  615,   64,  627,
       75,   76,   82,   87,   99,   83,  119,   92,  112,  124,
      106,  126,  140,  646,  646,  646,  646,  617,  646,  646,
      646,  629,  627,   80,  646,  646,    0,  646,  612,  609,
      646,  153,  646,    0,  594,  160,   78,  605,  646,  646,
      646,  646,  646,  601,  155,  145,  600,  151,  167,  165,
      180,  184,  599,  174,  181,  598,  191,  186,  187,  192,
      188,  189,  597,  596,  193,  203,  219,  225,  228,  594,

      217,  232,  242,  646,    0,  581,  580,  589,  248,  588,
      224,  254,  301,  256,  246,  587,  252,  260,  586,  585,
      108,  579,  577,  576,  253,  574,  258,  266,  282,  255,
      262,  268,  290,  278,  279,  566,  293,  322,  322,  284,
      319,  326,  329,  341,  330,  340,  562,  334,  333,  485,
      343,  369,  376,  424,  358,  349,  361,  394,  379,  363,
      280,  365,  342,  393,  400,  346,  395,  401,  382,  338,
      320,  406,  407,  312,  410,  411,  402,  408,  309,  420,
      421,  294,   41,   51,  646,   50,  415,  416,  276,  433,
      415,  436,  443,  414,  446,  274,  212,  469,  451,  434,

      458,  646,  454,  167,  430,  449,  472,  475,  479,  476,
      481,  477,  495,  486,  493,  463,  207,  465,  481,  473,
      480,  502,  503,  514,  201,  194,  153,  494,  520,  524,
      646,  504,  499,  500,  646,  528,  150,  538,  511,  146,
      541,  514,  646,  511,  544,  549,  646,   96,  518,  529,
       90,  554,  646,  531,  563,  542,   89,  646,  646,  611,
      614,  617,  620,  623,   89,  626
    } ;

static const flex_int16_t yy_def[267] =
    {   0,
      259,    1,  260,  260,  261,  261,  262,  262,  259,  259,
      259,  259,  259,  263,  259,  259,  264,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  263,  259,  259,  264,  259,  259,  259,
      259,  259,  259,  266,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  259,  266,  259,  259,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  259,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  259,
      259,  259,  259,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  259,
      265,  265,  259,  259,  259,  259,  259,  259,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  259,

      265,  259,  259,  259,  259,  259,  265,  265,  265,  265,
      265,  265,  259,  265,  265,  259,  265,  259,  259,  259,
      259,  265,  265,  265,  265,  265,  265,  259,  265,  265,
      259,  259,  259,  259,  259,  265,  265,  265,  259,  265,
      265,  259,  259,  259,  265,  265,  259,  265,  259,  259,
      265,  265,  259,  259,  265,  259,  265,  259,    0,  259,
      259,  259,  259,  259,  259,  259
    } ;

static const flex_int16_t yy_nxt[711] =
    {   0,
       10,   11,   12,   13,   14,   10,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   30,   31,   32,   33,   30,   30,   34,   30,
       35,   36,   37,   38,   39,   40,   41,   42,   30,   43,
       30,   15,   44,   29,   30,   30,   31,   32,   33,   30,
       30,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       30,   43,   30,   45,   47,   47,   55,   60,   55,   73,
       63,   61,   48,   48,   64,   65,  202,   66,   69,   70,
       73,   73,   55,  203,   55,  204,   67,   73,   73,  106,
      106,   74,   73,  107,   73,   73,   75,   73,  202,   76,

       77,   73,   82,   78,   73,  203,   79,  204,   80,   67,
       83,   73,   86,   73,   81,   84,   90,   73,   75,   87,
       85,   76,   77,   88,   73,   82,   78,   93,   79,   73,
       80,   73,   89,   83,  147,   86,   81,   84,   90,   91,
       94,   87,   85,   97,   98,   73,   88,   95,   96,   93,
       73,   73,   92,   99,   89,   73,   73,  147,   73,  100,
       73,  101,   91,   94,  102,   97,   98,  103,   62,   95,
       73,   96,   73,   65,   92,   66,   99,   67,  108,   73,
      109,  100,  110,  101,   67,   73,   73,  102,  113,   73,
      103,   73,   73,   73,   73,  111,   73,   73,   73,   73,

       67,  108,  109,  112,  110,  219,   73,   67,   73,  116,
      114,  113,   73,  117,  115,  122,  118,   73,  111,  121,
      123,  125,   73,  120,   73,  112,  124,  219,  119,   73,
       73,  116,  114,   73,  126,  117,  115,   73,  122,  118,
      127,  121,  123,  128,  125,  120,  130,   73,  124,  136,
      119,   73,  131,   73,  129,  132,  126,   73,   73,   73,
       73,   73,  127,   73,  133,   73,  128,   73,  135,  130,
      134,   73,  136,   73,  145,  131,  129,  132,  137,   73,
      143,   73,  144,   73,   73,  148,  133,   73,  146,   73,
      153,  135,  155,  134,  154,   73,  149,  145,   73,   73,

      150,  137,  138,  143,  144,  185,   73,  148,  157,  166,
      151,  146,  153,  156,   73,  155,  154,   73,  149,  158,
      152,  159,  150,  138,   73,   73,  139,   73,  185,  140,
      157,   73,  166,  151,   73,   73,  156,  141,   73,   73,
      142,  158,  152,   73,  159,   73,   73,  160,   73,  139,
      161,   73,  140,  169,   73,  164,  167,  168,  162,  141,
      165,  163,  142,   73,  170,  171,   73,  172,  175,  188,
      160,  174,  173,  161,   73,  176,  169,  164,  167,  168,
      162,   73,  165,  163,   73,  179,  170,   73,  171,  172,
      175,  177,  188,  174,  173,  180,  183,  176,   73,   73,

       73,  184,  186,  187,  182,   73,   73,   73,  179,  178,
      193,   73,   73,   73,  177,   73,   73,  181,  183,   73,
       73,  180,  192,  184,  186,  187,   73,  182,  189,   73,
      191,  178,  190,  193,  194,  195,  205,  197,   73,  198,
      181,   73,  196,  200,  206,  192,  199,  211,   73,  201,
      189,   73,  191,  208,  190,  207,   73,  194,  195,  205,
      197,  198,  216,   73,  196,  220,  200,  206,  199,  211,
      213,  209,  201,  210,   73,  208,  218,   73,  207,  221,
       73,   73,   73,  212,   73,  216,   73,  220,  215,  217,
       73,   73,  214,  209,  231,  210,  213,  223,   73,  218,

      225,  221,  232,  233,  235,  212,  234,   73,   73,  222,
      215,  217,  224,  226,  229,  214,  231,  227,  228,   73,
      223,  230,  239,  225,  232,   73,  233,  235,  234,   73,
      236,  222,  242,   73,  224,  226,  243,  229,  244,  227,
      237,  228,  247,   73,  230,  239,   73,  249,  250,   73,
      253,  240,  238,  236,   73,  242,  241,  254,  243,   73,
      244,  245,  237,  256,  247,  248,  258,   73,   73,  249,
      250,   73,  253,  240,  238,  246,  251,  252,  241,   73,
      254,   73,   73,  245,   73,  256,  255,  257,  248,  258,
       73,   73,   73,   73,   73,  107,  107,  246,  251,   73,

      252,   73,   73,   73,   73,   73,   73,   68,  255,   62,
      257,   46,   46,   46,   49,   49,   49,   51,   51,   51,
       54,   54,   54,   57,   60,   57,  105,   59,  105,   53,
       52,  104,   73,   72,   71,   68,   62,   59,   58,   56,
       53,   52,  259,   50,   50,    9,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259
    } ;

static const flex_int16_t yy_chk[711] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   14,   21,   14,   29,
       23,   21,    3,    4,   23,   24,  183,   24,   26,   26,
       31,   32,   54,  184,   54,  186,   24,   33,   36,   67,
       67,  265,   34,   67,  257,  251,   29,   38,  183,   29,

       29,  248,   33,   31,   35,  184,   32,  186,   32,   24,
       33,   41,   34,  121,   32,   33,   36,   39,   29,   34,
       33,   29,   29,   35,   37,   33,   31,   38,   32,   40,
       32,   42,   35,   33,  121,   34,   32,   33,   36,   37,
       39,   34,   33,   41,   41,   43,   35,   39,   40,   38,
       76,  240,   37,   42,   35,  237,   78,  121,  227,   42,
       75,   42,   37,   39,   43,   41,   41,   43,   62,   39,
       80,   40,   79,   66,   37,   66,   42,   62,   75,   84,
       76,   42,   78,   42,   66,   81,   85,   43,   80,   82,
       43,   88,   89,   91,   92,   79,   87,   90,   95,  226,

       62,   75,   76,   79,   78,  204,  225,   66,   96,   84,
       81,   80,  217,   85,   82,   90,   87,  197,   79,   89,
       91,   95,  101,   88,   97,   79,   92,  204,   87,  111,
       98,   84,   81,   99,   96,   85,   82,  102,   90,   87,
       96,   89,   91,   97,   95,   88,   98,  103,   92,  111,
       87,  115,   99,  109,   97,  101,   96,  117,  125,  112,
      130,  114,   96,  127,  102,  118,   97,  131,  109,   98,
      103,  128,  111,  132,  117,   99,   97,  101,  112,  196,
      114,  189,  115,  134,  135,  125,  102,  129,  118,  140,
      130,  109,  132,  103,  131,  133,  127,  117,  137,  182,

      128,  112,  113,  114,  115,  161,  113,  125,  134,  140,
      129,  118,  130,  133,  179,  132,  131,  174,  127,  135,
      129,  137,  128,  138,  141,  171,  113,  139,  161,  113,
      134,  142,  140,  129,  143,  145,  133,  113,  149,  148,
      113,  135,  129,  170,  137,  146,  144,  138,  151,  113,
      138,  166,  113,  142,  156,  139,  141,  141,  138,  113,
      139,  138,  113,  155,  143,  144,  157,  145,  149,  163,
      138,  148,  146,  138,  152,  151,  142,  139,  141,  141,
      138,  153,  139,  138,  159,  157,  143,  169,  144,  145,
      149,  152,  163,  148,  146,  158,  160,  151,  164,  158,

      167,  160,  162,  162,  159,  165,  168,  177,  157,  153,
      169,  172,  173,  178,  152,  175,  176,  158,  160,  194,
      191,  180,  168,  160,  162,  162,  181,  159,  164,  154,
      167,  153,  165,  169,  172,  173,  187,  176,  190,  177,
      158,  192,  175,  180,  188,  168,  178,  194,  193,  181,
      164,  195,  167,  191,  165,  190,  199,  172,  173,  187,
      176,  177,  200,  201,  175,  205,  180,  188,  178,  194,
      198,  192,  181,  193,  198,  191,  203,  207,  190,  206,
      208,  210,  212,  195,  209,  200,  211,  205,  199,  201,
      150,  214,  198,  192,  216,  193,  213,  208,  215,  203,

      210,  206,  218,  219,  221,  195,  220,  222,  223,  207,
      199,  201,  209,  211,  214,  198,  216,  212,  213,  224,
      208,  215,  228,  210,  218,  229,  219,  221,  220,  230,
      222,  207,  232,  236,  209,  211,  233,  214,  234,  212,
      223,  213,  239,  238,  215,  228,  241,  242,  244,  245,
      249,  229,  224,  222,  246,  232,  230,  250,  233,  252,
      234,  236,  223,  254,  239,  241,  256,  147,  255,  242,
      244,  136,  249,  229,  224,  238,  245,  246,  230,  126,
      250,  124,  123,  236,  122,  254,  252,  255,  241,  256,
      120,  119,  116,  110,  108,  107,  106,  238,  245,  100,

      246,   94,   93,   86,   83,   77,   74,   68,  252,   65,
      255,  260,  260,  260,  261,  261,  261,  262,  262,  262,
      263,  263,  263,  264,   60,  264,  266,   59,  266,   53,
       52,   48,   30,   28,   27,   25,   22,   20,   19,   16,
       12,   11,    9,    6,    5,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/cai/projects/basic/compiler/qblex.ll"
/*
    lexcial analize for QBASIC
	Copyright (C) 2009-2010 Thomas Larsen and Pedro Sá.
	Copyright (C) 1995-2005 Marc-Oliver Ihm.
    Copyright (C) 2012  microcai <microcai@fedoraproject.org>

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1



#line 33 "/home/cai/projects/basic/compiler/qblex.ll"

#ifdef _WIN32
#include <io.h>
#endif

/* Include main header file. */
#include <cstring>

#include "qbc.h"
#include "ast.hpp"

/* Get tokens from parser library. */
#include "parser.hpp"

using namespace qb;

typedef parser::semantic_type YYSTYPE;
typedef parser::token token;

#define error printf
/* Local variables. */
int count = 0;                  /* for strings */

#line 751 "/home/cai/projects/basic/compiler/qblex.cpp"
#line 752 "/home/cai/projects/basic/compiler/qblex.cpp"

#define INITIAL 0
#define block_comment 1
#define remark 2
#define documentation 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
    yylval = yylval_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 63 "/home/cai/projects/basic/compiler/qblex.ll"


#line 983 "/home/cai/projects/basic/compiler/qblex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 646 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
#line 65 "/home/cai/projects/basic/compiler/qblex.ll"
{
   return token::tEOPROG;
}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 69 "/home/cai/projects/basic/compiler/qblex.ll"
{
	BEGIN(remark);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "/home/cai/projects/basic/compiler/qblex.ll"
{
   BEGIN (block_comment);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "/home/cai/projects/basic/compiler/qblex.ll"
/* eat comment */ {

}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "/home/cai/projects/basic/compiler/qblex.ll"
/* eat comment */ {
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 84 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tNEWLINE;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 86 "/home/cai/projects/basic/compiler/qblex.ll"
{
	yylineno += strlen(yytext);
   return token::tNEWLINE;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tSUBEND;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tFUNCTIONEND;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tENDWHILE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tENDFOR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 95 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tARRAYDIM;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tENDWHILE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tWHILE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 98 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tENDIF;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tSTRUCTDIM;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tENDSTRUCDIM;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tFUNCTION;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tSUB;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tTHEN;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tELSE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "/home/cai/projects/basic/compiler/qblex.ll"
{/*printf("if begin ! ======\n"); */return token::tIF;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tELSEIF;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tRETURN;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tFOR;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tTO;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tSTEP;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tSTR;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tLONG;/* variables type*/
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 117 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tAS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tDIM;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tLET;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 122 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tPRINT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 124 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tDREF;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 126 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tPOW;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 128 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tAND;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 129 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tAND;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 131 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tMOD;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 132 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tOR;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 133 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tEQU;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 134 "/home/cai/projects/basic/compiler/qblex.ll"
return '=';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tGEQ;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tGTN;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tLEQ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tLTN;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tNEQ;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 141 "/home/cai/projects/basic/compiler/qblex.ll"
return token::tNOT;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "/home/cai/projects/basic/compiler/qblex.ll"
return '*';
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 146 "/home/cai/projects/basic/compiler/qblex.ll"
/* eat whitespace */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 148 "/home/cai/projects/basic/compiler/qblex.ll"
{
   return yytext[1 - 1];
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 152 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->number = strtod ("inf", NULL);
   return token::tNUMBER;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 157 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->number = strtod ("nan", NULL);
   return token::tNUMBER;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 162 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->number = 3.1415926535897932;
   return token::tNUMBER;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 167 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->number = 2.7182818284590452;
   return token::tNUMBER;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 172 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->number = 1;
   return token::tNUMBER;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 177 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->number = 0;
   return token::tNUMBER;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 184 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->integer = atol (yytext);
   return token::tInteger;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 189 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->integer = atol (yytext);
   return token::tInteger;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 195 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->integer = atol (yytext);
   return token::tInteger;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 200 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->number = strtod (yytext, NULL);
   return token::tNUMBER;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 205 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->id = new std::string (yytext);
   return token::tID;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 210 "/home/cai/projects/basic/compiler/qblex.ll"
{
   yylval->id = new std::string (yytext);
   return token::tID;
}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 216 "/home/cai/projects/basic/compiler/qblex.ll"
{
   if (yytext[yyleng - 1] == '\n') {
      printf ("string not terminated");
   }
   for (count = 0; yytext[(yyleng - count - 1) - 1] == '\\'; count++);
   if (count % 2) {
      yyless (yyleng - 1);
      yymore ();
   }
   else {
      yylval->string = strdup (yytext + 1);
      *(yylval->string + yyleng - 2) = '\0';
      replace (yylval->string);
      return token::tSTRING;
   }
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 233 "/home/cai/projects/basic/compiler/qblex.ll"
{
   return yytext[1 - 1];
}
	YY_BREAK

case 64:
YY_RULE_SETUP
#line 239 "/home/cai/projects/basic/compiler/qblex.ll"
BEGIN (INITIAL);
	YY_BREAK
case YY_STATE_EOF(block_comment):
#line 241 "/home/cai/projects/basic/compiler/qblex.ll"
error ("block comment not terminated");
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 243 "/home/cai/projects/basic/compiler/qblex.ll"

	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 244 "/home/cai/projects/basic/compiler/qblex.ll"
yylineno ++;
	YY_BREAK


case 67:
YY_RULE_SETUP
#line 249 "/home/cai/projects/basic/compiler/qblex.ll"

	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 251 "/home/cai/projects/basic/compiler/qblex.ll"
BEGIN(INITIAL);
	YY_BREAK

case 69:
YY_RULE_SETUP
#line 254 "/home/cai/projects/basic/compiler/qblex.ll"
ECHO;
	YY_BREAK
#line 1475 "/home/cai/projects/basic/compiler/qblex.cpp"
case YY_STATE_EOF(remark):
case YY_STATE_EOF(documentation):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 259);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 254 "/home/cai/projects/basic/compiler/qblex.ll"


/* Report an error. */
void yyerror (char *msg) {
   /* Report the error. */
   if (*yytext == '\n' || *yytext == '\0') {
      printf ("%s at end of line", msg);
   }
   else {
      printf ("%s at \"%s\"", msg, yytext);
   }

   /* Return. */
   return;
}

/* Replace escape characters. */
char *replace (char *string) {
   char *from, *to, *pointer;
   char hexdigits[] = "0123456789abcdef";
   int value;

   /* Initialise. */
   from = string;
   to = string;

   /* Replace. */
   while (*from) {
      if (*from == '\\') {
         from++;
         switch (*from) {
            case 'n':
               *to = '\n';
               break;
            case 't':
               *to = '\t';
               break;
            case 'v':
               *to = '\v';
               break;
            case 'b':
               *to = '\b';
               break;
            case 'r':
               *to = '\r';
               break;
            case 'f':
               *to = '\f';
               break;
            case 'a':
               *to = '\a';
               break;
            case '\\':
               *to = '\\';
               break;
            case '\?':
               *to = '\?';
               break;
            case '\'':
               *to = '\'';
               break;
            case '\"':
               *to = '\"';
               break;
            case 'x':
               value = 0;
               if ((pointer =
                    std::strchr (hexdigits, tolower (*(from + 1))))
                   && pointer - hexdigits < 16) {
                  from++;
                  value = pointer - hexdigits;
                  if ((pointer =
                       std::strchr (hexdigits, tolower (*(from + 1))))
                      && pointer - hexdigits < 16) {
                     from++;
                     value *= 16;
                     value += pointer - hexdigits;
                  }
               }
               *to = value;
               break;
            default:
               *to = '\\';
               to++;
               *to = *from;
               break;
         }
      }
      else
         *to = *from;
      from++;
      to++;
   }
   *to = '\0';

   /* Return. */
   return string;
}

